export const books = [
  {
    name: 'React.js Быстрый старт',
    cover: 'assets/reactjs.png',
    description: 'Незаменимая вводная книга по технологии React для взыскательных JavaScript-разработчиков. Все самое интересное о сверхпопулярном инструменте от компании Facebook. В книге рассмотрены основные концепции высокопроизводительного программирования при помощи React, реальные примеры кода и доступные блок-схемы.',
    author: 'Стефанов Стоян',
    publisher: 'Питер',
    codeIsbn: 9785496030038,
    year: 2017,
    pages: 304,
    rating: Math.round(Math.random() * 5),
    comment: '',
    personalNotes: ''
  },
  {
    name: 'SVG Animations',
    cover: 'assets/svgAnimation.jpg',
    description: 'SVG is extremely powerful, with its reduced HTTP requests and crispness on any display. It becomes increasingly more interesting as you explore its capabilities for responsive animation and performance boons. When you animate SVG, you must be aware of normal image traits like composition, color, implementation, and optimization. But when you animate, it increases the complexity of each of these factors exponentially.',
    author: 'Sarah Drasner',
    publisher: 'O\'Reilly Media, Inc.',
    codeIsbn: 9781491939703,
    year: 2017,
    pages: null,
    rating: Math.round(Math.random() * 5),
    comment: '',
    personalNotes: ''
  },
  {
    name: 'JavaScript. Карманный справочник',
    cover: 'assets/js.png',
    description: 'JavaScript - популярнейший язык программирования, который уже более 15 лет применяется для написания сценариев интерактивных веб-страниц. В книге представлены самые важные сведения о синтаксисе языка и показаны примеры его практического применения. Несмотря на малый объем карманного издания, в нем содержится все, что необходимо знать для разработки профессиональных веб-приложений.',
    author: 'Флэнаган Дэвид',
    publisher: 'Вильямс',
    codeIsbn: 9785845919489,
    year: 2018,
    pages: 320,
    rating: Math.round(Math.random() * 5),
    comment: '',
    personalNotes: ''
  },
  {
    name: 'Speaking JavaScript: An In-Depth Guide for Programmers',
    cover: 'assets/jsSpeaking.png',
    description: 'This book has been written for programmers, by a programmer. In order to understand it, you should already know object-oriented programming, for example, via a mainstream programming language such as Java, PHP, C++, Python, Ruby, Objective-C, Swift, C#, or Perl.',
    author: 'Dr. Axel Rauschmayer',
    publisher: 'Amazon, O’Reilly',
    codeIsbn: 9785845919491,
    year: 2014,
    pages: null,
    rating: Math.round(Math.random() * 5),
    comment: '',
    personalNotes: ''
  },
  {
    name: 'Секреты JavaScript ниндзя',
    cover: 'assets/jsSecrets.jpg',
    description: 'Особое мнение JavaScript было очевидно не всегда, но теперь оно несомненнно. Ныне JavaScript стал одним из самых важных и широко применяемых языков программирования',
    author: 'Джон Резиг, Беэр Бибо',
    publisher: 'Диалектика',
    codeIsbn: 9785990891180,
    year: 2017,
    pages: null,
    rating: Math.round(Math.random() * 5),
    comment: '',
    personalNotes: ''
  },
];
